import { type NextPage } from "next";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Head from "next/head";
import Header from "~/components/Header";
import Analytics from "~/features/analytics";
import { useEffect } from "react";
import Tasks from "~/features/tasks";

async function notificationPermission() {
    const permission = await Notification.requestPermission();
    if (permission === "granted") {
        console.log("Notification permission granted.");
    } else {
        console.log("Unable to get permission to notify.");
    }
}

const Home: NextPage = () => {
    useEffect(() => {
        void notificationPermission();
    }, []);

    return (
        <>
            <Head>
                <title>Tasks App - Lief Assignment</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="sm:max-w-xl    mx-auto ">
                <Header />

                <Tabs defaultValue="tasks" className="m-5 mx-2.5 sm:mx-0">
                    <TabsList className="w-full mb-2.5 sticky top-5 z-10 shadow-sm   border bg-orange-100">
                        <TabsTrigger className="flex-1" value="tasks">Tasks</TabsTrigger>
                        <TabsTrigger className="flex-1" value="analytics">
                            Analytics
                        </TabsTrigger>
                    </TabsList>
                    <TabsContent value="tasks">
                        <Tasks />
                    </TabsContent>
                    <TabsContent value="analytics">
                        <Analytics />
                    </TabsContent>
                </Tabs>
            </main>
        </>
    );
};

export default Home;
