import { type NextPage } from "next";
import Head from "next/head";
import CreateTask from "~/components/CreateTask";
import Header from "~/components/Header";
import Tasklist from "~/components/TaskList";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Tasks App - Lief Assignment</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="sm:max-w-xl    mx-auto ">
                <Header />
                <h1 className="text-3xl font-bold">Tasks</h1>
                <section className="space-y-5">
                    <CreateTask />
                    <Tasklist />
                </section>
            </main>
        </>
    );
};

export default Home;
